### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by abornite** [RXVAN/simple-trampoline#1]

**Comment by RXVAN** [comment]
rather unfortunate. Works on my machine.

**Comment by abornite** [comment]
Proof please

**Comment by RXVAN** [comment]
erm well you see there was a fire in the server and i lost 200 TB data. please standby

**Comment by abornite** [comment]
https://www.hse.gov.uk/toolbox/fire.htm

**Comment by RXVAN** [comment]
shoot i forgot to follow each and every one of those 😅

**Comment by abornite** [comment]
Please make sure to do so in the future, as doing so will greatly reduce future risk of data loss due to fire.
